//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseWebapi.ModelContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered
    {
        public int OrId { get; set; }
        public int PId { get; set; }
        public string OrUName { get; set; }
        public string OrAdress { get; set; }
        public System.DateTime dateTime { get; set; }
    }
}
