//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseWebapi.ModelContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public int PStocks { get; set; }
        public double PPrice { get; set; }
        public string PImage { get; set; }
        public int SuId { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
